-- Liga de fútbol: tablas, claves y datos de ejemplo (Oracle)
DROP TABLE GOLES;
DROP TABLE PARTIDOS;
DROP TABLE JUGADORES;
DROP TABLE EQUIPOS;

CREATE TABLE EQUIPOS (
    COD_EQUIPO  NUMBER(2) PRIMARY KEY,
    NOMBRE      VARCHAR2(30) NOT NULL UNIQUE,
    CIUDAD      VARCHAR2(30)
);

CREATE TABLE JUGADORES (
    COD_JUGADOR NUMBER(4) PRIMARY KEY,
    NOMBRE      VARCHAR2(40) NOT NULL,
    DORSAL      NUMBER(2) CHECK (DORSAL BETWEEN 1 AND 99),
    COD_EQUIPO  NUMBER(2) NOT NULL REFERENCES EQUIPOS(COD_EQUIPO)
);

CREATE TABLE PARTIDOS (
    COD_PARTIDO NUMBER(3) PRIMARY KEY,
    FECHA       DATE NOT NULL,
    LOCAL       NUMBER(2) NOT NULL REFERENCES EQUIPOS(COD_EQUIPO),
    VISITANTE   NUMBER(2) NOT NULL REFERENCES EQUIPOS(COD_EQUIPO),
    CHECK (LOCAL <> VISITANTE)
);

CREATE TABLE GOLES (
    COD_PARTIDO NUMBER(3) REFERENCES PARTIDOS(COD_PARTIDO),
    COD_JUGADOR NUMBER(4) REFERENCES JUGADORES(COD_JUGADOR),
    MINUTO      NUMBER(3) CHECK (MINUTO BETWEEN 1 AND 120),
    PRIMARY KEY (COD_PARTIDO, COD_JUGADOR, MINUTO)
);

INSERT INTO EQUIPOS VALUES (1, 'Leganés CF', 'Leganés');
INSERT INTO EQUIPOS VALUES (2, 'Getafe Club', 'Getafe');
INSERT INTO EQUIPOS VALUES (3, 'Alcorcón United', 'Alcorcón');

INSERT INTO JUGADORES VALUES (1, 'Pablo Ruiz', 9, 1);
INSERT INTO JUGADORES VALUES (2, 'Marcos Gil', 10, 1);
INSERT INTO JUGADORES VALUES (3, 'Dani Soto', 7, 2);
INSERT INTO JUGADORES VALUES (4, 'Luis Vega', 11, 2);
INSERT INTO JUGADORES VALUES (5, 'Hugo Prieto', 9, 3);

INSERT INTO PARTIDOS VALUES (1, TO_DATE('06/10/2025','DD/MM/YYYY'), 1, 2);
INSERT INTO PARTIDOS VALUES (2, TO_DATE('13/10/2025','DD/MM/YYYY'), 2, 3);
INSERT INTO PARTIDOS VALUES (3, TO_DATE('20/10/2025','DD/MM/YYYY'), 3, 1);

INSERT INTO GOLES VALUES (1, 1, 12);
INSERT INTO GOLES VALUES (1, 2, 55);
INSERT INTO GOLES VALUES (1, 3, 70);
INSERT INTO GOLES VALUES (2, 4, 33);
INSERT INTO GOLES VALUES (2, 5, 80);
INSERT INTO GOLES VALUES (3, 5, 5);
INSERT INTO GOLES VALUES (3, 1, 60);
INSERT INTO GOLES VALUES (3, 1, 88);
COMMIT;
