-- 1. Goleadores ordenados por número de goles
SELECT J.NOMBRE, E.NOMBRE EQUIPO, COUNT(*) GOLES
FROM GOLES G, JUGADORES J, EQUIPOS E
WHERE G.COD_JUGADOR = J.COD_JUGADOR AND J.COD_EQUIPO = E.COD_EQUIPO
GROUP BY J.NOMBRE, E.NOMBRE
ORDER BY GOLES DESC;

-- 2. Equipos que no han marcado ningún gol
SELECT NOMBRE FROM EQUIPOS E
WHERE NOT EXISTS (SELECT 1 FROM GOLES G, JUGADORES J
                  WHERE G.COD_JUGADOR = J.COD_JUGADOR AND J.COD_EQUIPO = E.COD_EQUIPO);

-- 3. Partidos con su resultado
CREATE OR REPLACE VIEW V_RESULTADOS AS
SELECT P.COD_PARTIDO, P.FECHA, EL.NOMBRE LOCAL, EV.NOMBRE VISITANTE,
       (SELECT COUNT(*) FROM GOLES G, JUGADORES J
         WHERE G.COD_PARTIDO = P.COD_PARTIDO AND G.COD_JUGADOR = J.COD_JUGADOR
           AND J.COD_EQUIPO = P.LOCAL) GOLES_LOCAL,
       (SELECT COUNT(*) FROM GOLES G, JUGADORES J
         WHERE G.COD_PARTIDO = P.COD_PARTIDO AND G.COD_JUGADOR = J.COD_JUGADOR
           AND J.COD_EQUIPO = P.VISITANTE) GOLES_VISITANTE
FROM PARTIDOS P, EQUIPOS EL, EQUIPOS EV
WHERE P.LOCAL = EL.COD_EQUIPO AND P.VISITANTE = EV.COD_EQUIPO;

SELECT * FROM V_RESULTADOS ORDER BY FECHA;

-- 4. Jugadores que han marcado más de un gol en un mismo partido
SELECT J.NOMBRE, G.COD_PARTIDO, COUNT(*) GOLES
FROM GOLES G, JUGADORES J
WHERE G.COD_JUGADOR = J.COD_JUGADOR
GROUP BY J.NOMBRE, G.COD_PARTIDO
HAVING COUNT(*) > 1;
