-- Función que devuelve los puntos de un equipo (3 victoria, 1 empate)
CREATE OR REPLACE FUNCTION PUNTOS_EQUIPO(P_EQUIPO NUMBER) RETURN NUMBER IS
    V_PUNTOS NUMBER := 0;
BEGIN
    FOR R IN (SELECT P.LOCAL, P.VISITANTE, V.GOLES_LOCAL GL, V.GOLES_VISITANTE GV
              FROM PARTIDOS P, V_RESULTADOS V
              WHERE P.COD_PARTIDO = V.COD_PARTIDO
                AND (P.LOCAL = P_EQUIPO OR P.VISITANTE = P_EQUIPO)) LOOP
        IF R.GL = R.GV THEN
            V_PUNTOS := V_PUNTOS + 1;
        ELSIF (R.LOCAL = P_EQUIPO AND R.GL > R.GV)
           OR (R.VISITANTE = P_EQUIPO AND R.GV > R.GL) THEN
            V_PUNTOS := V_PUNTOS + 3;
        END IF;
    END LOOP;
    RETURN V_PUNTOS;
END PUNTOS_EQUIPO;
/

-- Procedimiento que muestra la clasificación
CREATE OR REPLACE PROCEDURE MOSTRAR_CLASIFICACION IS
    CURSOR C IS SELECT COD_EQUIPO, NOMBRE, PUNTOS_EQUIPO(COD_EQUIPO) PTS
                FROM EQUIPOS ORDER BY 3 DESC, NOMBRE;
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(R.NOMBRE, 20) || R.PTS || ' pts');
    END LOOP;
END;
/

-- Trigger: no permitir goles en minuto superior a 120 ni de jugadores ajenos al partido
CREATE OR REPLACE TRIGGER TR_GOL_VALIDO
BEFORE INSERT ON GOLES
FOR EACH ROW
DECLARE
    V_EQ NUMBER;
    V_N  NUMBER;
BEGIN
    SELECT COD_EQUIPO INTO V_EQ FROM JUGADORES WHERE COD_JUGADOR = :NEW.COD_JUGADOR;
    SELECT COUNT(*) INTO V_N FROM PARTIDOS
     WHERE COD_PARTIDO = :NEW.COD_PARTIDO AND (LOCAL = V_EQ OR VISITANTE = V_EQ);
    IF V_N = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El jugador no pertenece a ninguno de los equipos del partido');
    END IF;
END;
/

SET SERVEROUTPUT ON
EXEC MOSTRAR_CLASIFICACION;
