-- Biblioteca: socios, libros y préstamos (Oracle)
DROP TABLE PRESTAMOS;
DROP TABLE LIBROS;
DROP TABLE SOCIOS;

CREATE TABLE SOCIOS (
    COD_SOCIO  NUMBER(4) PRIMARY KEY,
    NOMBRE     VARCHAR2(40) NOT NULL,
    EMAIL      VARCHAR2(50) UNIQUE,
    SANCIONADO CHAR(1) DEFAULT 'N' CHECK (SANCIONADO IN ('S','N'))
);

CREATE TABLE LIBROS (
    COD_LIBRO  NUMBER(4) PRIMARY KEY,
    TITULO     VARCHAR2(60) NOT NULL,
    AUTOR      VARCHAR2(40),
    GENERO     VARCHAR2(20),
    EJEMPLARES NUMBER(2) DEFAULT 1 CHECK (EJEMPLARES >= 0)
);

CREATE TABLE PRESTAMOS (
    COD_PRESTAMO  NUMBER(5) PRIMARY KEY,
    COD_SOCIO     NUMBER(4) NOT NULL REFERENCES SOCIOS,
    COD_LIBRO     NUMBER(4) NOT NULL REFERENCES LIBROS,
    F_PRESTAMO    DATE DEFAULT SYSDATE,
    F_DEVOLUCION  DATE
);

INSERT INTO SOCIOS VALUES (1, 'Lucía Ramos', 'lucia@mail.com', 'N');
INSERT INTO SOCIOS VALUES (2, 'Pablo Gil', 'pablo@mail.com', 'N');
INSERT INTO SOCIOS VALUES (3, 'Marta Soto', 'marta@mail.com', 'N');

INSERT INTO LIBROS VALUES (1, 'El Quijote', 'Cervantes', 'Novela', 2);
INSERT INTO LIBROS VALUES (2, 'Rimas y Leyendas', 'Bécquer', 'Poesía', 1);
INSERT INTO LIBROS VALUES (3, 'Fundamentos de Java', 'Varios', 'Informática', 3);
INSERT INTO LIBROS VALUES (4, 'La Celestina', 'Rojas', 'Novela', 1);

INSERT INTO PRESTAMOS VALUES (1, 1, 1, SYSDATE-40, SYSDATE-30);
INSERT INTO PRESTAMOS VALUES (2, 2, 3, SYSDATE-20, NULL);
INSERT INTO PRESTAMOS VALUES (3, 3, 2, SYSDATE-5, NULL);
COMMIT;
