-- 1. Libros prestados actualmente (sin devolver) con el nombre del socio
SELECT L.TITULO, S.NOMBRE SOCIO, P.F_PRESTAMO
FROM PRESTAMOS P, LIBROS L, SOCIOS S
WHERE P.COD_LIBRO = L.COD_LIBRO AND P.COD_SOCIO = S.COD_SOCIO
  AND P.F_DEVOLUCION IS NULL;

-- 2. Préstamos con retraso (más de 15 días sin devolver)
SELECT S.NOMBRE, L.TITULO, TRUNC(SYSDATE - P.F_PRESTAMO) DIAS
FROM PRESTAMOS P, LIBROS L, SOCIOS S
WHERE P.COD_LIBRO = L.COD_LIBRO AND P.COD_SOCIO = S.COD_SOCIO
  AND P.F_DEVOLUCION IS NULL AND SYSDATE - P.F_PRESTAMO > 15;

-- 3. Número de préstamos por género, de mayor a menor
SELECT L.GENERO, COUNT(*) PRESTAMOS
FROM PRESTAMOS P JOIN LIBROS L ON P.COD_LIBRO = L.COD_LIBRO
GROUP BY L.GENERO
ORDER BY PRESTAMOS DESC;

-- 4. Socios que nunca han pedido un libro
SELECT NOMBRE FROM SOCIOS
WHERE COD_SOCIO NOT IN (SELECT COD_SOCIO FROM PRESTAMOS);

-- 5. Los 3 libros más prestados
SELECT * FROM (
    SELECT L.TITULO, COUNT(*) VECES
    FROM PRESTAMOS P JOIN LIBROS L ON P.COD_LIBRO = L.COD_LIBRO
    GROUP BY L.TITULO ORDER BY VECES DESC
) WHERE ROWNUM <= 3;
