-- Procedimiento para prestar un libro: comprueba ejemplares y sanciones
CREATE OR REPLACE PROCEDURE PRESTAR_LIBRO(P_SOCIO NUMBER, P_LIBRO NUMBER) IS
    V_EJEMPLARES LIBROS.EJEMPLARES%TYPE;
    V_SANCION    SOCIOS.SANCIONADO%TYPE;
    V_SIGUIENTE  NUMBER;
BEGIN
    SELECT SANCIONADO INTO V_SANCION FROM SOCIOS WHERE COD_SOCIO = P_SOCIO;
    IF V_SANCION = 'S' THEN
        RAISE_APPLICATION_ERROR(-20010, 'El socio está sancionado');
    END IF;

    SELECT EJEMPLARES INTO V_EJEMPLARES FROM LIBROS WHERE COD_LIBRO = P_LIBRO FOR UPDATE;
    IF V_EJEMPLARES = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'No quedan ejemplares disponibles');
    END IF;

    SELECT NVL(MAX(COD_PRESTAMO), 0) + 1 INTO V_SIGUIENTE FROM PRESTAMOS;
    INSERT INTO PRESTAMOS (COD_PRESTAMO, COD_SOCIO, COD_LIBRO) VALUES (V_SIGUIENTE, P_SOCIO, P_LIBRO);
    UPDATE LIBROS SET EJEMPLARES = EJEMPLARES - 1 WHERE COD_LIBRO = P_LIBRO;
    DBMS_OUTPUT.PUT_LINE('Préstamo ' || V_SIGUIENTE || ' registrado');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20012, 'Socio o libro inexistente');
END PRESTAR_LIBRO;
/

-- Procedimiento para devolver: marca la fecha y repone el ejemplar
CREATE OR REPLACE PROCEDURE DEVOLVER_LIBRO(P_PRESTAMO NUMBER) IS
    V_LIBRO PRESTAMOS.COD_LIBRO%TYPE;
BEGIN
    UPDATE PRESTAMOS SET F_DEVOLUCION = SYSDATE
    WHERE COD_PRESTAMO = P_PRESTAMO AND F_DEVOLUCION IS NULL
    RETURNING COD_LIBRO INTO V_LIBRO;

    UPDATE LIBROS SET EJEMPLARES = EJEMPLARES + 1 WHERE COD_LIBRO = V_LIBRO;
    DBMS_OUTPUT.PUT_LINE('Libro devuelto');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('El préstamo no existe o ya estaba devuelto');
END DEVOLVER_LIBRO;
/

-- Trigger: sanciona al socio que tiene 3 o más préstamos sin devolver
CREATE OR REPLACE TRIGGER TR_SANCION_SOCIO
AFTER INSERT ON PRESTAMOS
BEGIN
    UPDATE SOCIOS SET SANCIONADO = 'S'
    WHERE COD_SOCIO IN (SELECT COD_SOCIO FROM PRESTAMOS
                        WHERE F_DEVOLUCION IS NULL
                        GROUP BY COD_SOCIO HAVING COUNT(*) >= 3);
END;
/

SET SERVEROUTPUT ON
EXEC PRESTAR_LIBRO(1, 3);
EXEC DEVOLVER_LIBRO(2);
